import type { Metadata, Viewport } from "next";
import { publicConfig } from "@/config/env";
import { SkipToContent } from "@/components/layout/SkipToContent";
import { RAW_COLORS } from "@/theme/tokens";
import { ServiceWorkerManager } from "@/features/pwa/components/ServiceWorkerManager";
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: {
    default: publicConfig.appName,
    template: `%s · ${publicConfig.appName}`,
  },
  description: "Track personal and shared expenses, accounts, and settlements.",
  applicationName: publicConfig.appName,
  formatDetection: { telephone: false },

  // Generated by src/app/manifest.ts. Without this link the browser never offers to
  // install, however complete the manifest itself is.
  manifest: "/manifest.webmanifest",

  icons: {
    icon: [
      { url: "/favicon.ico", sizes: "32x32" },
      { url: "/icons/icon.svg", type: "image/svg+xml" },
      { url: "/icons/icon-192.png", sizes: "192x192", type: "image/png" },
    ],
    // iOS ignores manifest icons for the home screen and reads this instead.
    apple: [{ url: "/icons/apple-touch-icon.png", sizes: "180x180", type: "image/png" }],
  },

  /**
   * iOS standalone behaviour. Safari does not read `display: "standalone"` from the
   * manifest, so without this the installed app opens in a Safari chrome with an address
   * bar — which is the single most common reason an iPhone "install" feels wrong.
   */
  appleWebApp: {
    capable: true,
    title: publicConfig.appShortName,
    statusBarStyle: "default",
  },

  /**
   * Next 15 renders `appleWebApp.capable` as the standardised
   * `mobile-web-app-capable`, which iOS below 16.4 does not read. Those versions launch
   * the installed app in a Safari window with an address bar unless the legacy tag is
   * present, so it is declared explicitly. Verified by inspecting the rendered head — see
   * docs/updates/GROUP-16-PWA.md.
   */
  other: {
    "apple-mobile-web-app-capable": "yes",
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  // Zoom stays enabled: disabling it breaks accessibility for low-vision users.
  maximumScale: 5,
  // Extends under the iPhone's rounded corners and home indicator, which is what makes an
  // installed app look native rather than letterboxed.
  viewportFit: "cover",
  themeColor: RAW_COLORS.surface,
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <SkipToContent />
          {/*
            Above the route content and outside both route groups, so the worker is
            registered on the sign-in screen too. Caching the shell before the first
            sign-in is what makes the first offline launch work at all.
          */}
          <ServiceWorkerManager />
          {children}
        </Providers>
      </body>
    </html>
  );
}
