import type { Metadata, Viewport } from "next";
import { publicConfig } from "@/config/env";
import { SkipToContent } from "@/components/layout/SkipToContent";
import { ColorModeScript } from "@/components/theme/ColorModeScript";
import { RAW_COLORS } from "@/theme/tokens";
import { ServiceWorkerManager } from "@/features/pwa/components/ServiceWorkerManager";
import { fontVariableClassName } from "./fonts";
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: {
    default: publicConfig.appName,
    template: `%s · ${publicConfig.appName}`,
  },
  description: "Track personal and shared expenses, accounts, and settlements.",
  applicationName: publicConfig.appName,
  formatDetection: { telephone: false },

  // Generated by src/app/manifest.ts. Without this link the browser never offers to
  // install, however complete the manifest itself is.
  manifest: "/manifest.webmanifest",

  icons: {
    icon: [
      { url: "/favicon.ico", sizes: "32x32" },
      { url: "/icons/icon.svg", type: "image/svg+xml" },
      { url: "/icons/icon-192.png", sizes: "192x192", type: "image/png" },
    ],
    // iOS ignores manifest icons for the home screen and reads this instead.
    apple: [{ url: "/icons/apple-touch-icon.png", sizes: "180x180", type: "image/png" }],
  },

  /**
   * iOS standalone behaviour. Safari does not read `display: "standalone"` from the
   * manifest, so without this the installed app opens in a Safari chrome with an address
   * bar — which is the single most common reason an iPhone "install" feels wrong.
   */
  appleWebApp: {
    capable: true,
    title: publicConfig.appShortName,
    statusBarStyle: "default",
  },

  /**
   * Next 15 renders `appleWebApp.capable` as the standardised
   * `mobile-web-app-capable`, which iOS below 16.4 does not read. Those versions launch
   * the installed app in a Safari window with an address bar unless the legacy tag is
   * present, so it is declared explicitly. Verified by inspecting the rendered head — see
   * docs/updates/GROUP-16-PWA.md.
   */
  other: {
    "apple-mobile-web-app-capable": "yes",
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  // Zoom stays enabled: disabling it breaks accessibility for low-vision users.
  maximumScale: 5,
  // Extends under the iPhone's rounded corners and home indicator, which is what makes an
  // installed app look native rather than letterboxed.
  viewportFit: "cover",

  /**
   * The colour the browser paints its own chrome, and the colour flashed before the app
   * renders. It matches the *page background* (`colors.paper`), not the card surface.
   *
   * Declared as a media-qualified pair so a no-JavaScript render, and the moment before the
   * inline script runs, still gets the right colour for the operating system's mode.
   *
   * That pair is not the whole story. It keys off `prefers-color-scheme`, which is wrong for
   * a user who has explicitly overridden the mode — light OS, dark app. So
   * `applyColorMode()` overwrites the `content` of **every** `theme-color` meta with the
   * resolved colour, both in the pre-paint script and whenever the mode changes. Whichever
   * tag the browser selects then carries the same value. See section 3.4 of
   * docs/design-tasks/updates/GROUP-24-DARK-MODE.md.
   */
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: RAW_COLORS.surface },
    { media: "(prefers-color-scheme: dark)", color: RAW_COLORS.darkSurface },
  ],
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    /*
      The font variables go on <html>, not <body>, so `--font-*` is in scope for anything
      that renders outside the body's subtree — portalled content and the `globalCss`
      selectors in src/theme/index.ts included.
    */
    /*
      `suppressHydrationWarning` is on <html> because ColorModeScript mutates this element's
      `class` and `style` before React hydrates. Without it React reports a mismatch on every
      dark-mode load — the server rendered only the font classes, the DOM now also has
      `dark` and a `color-scheme`. It is scoped to this one element's own attributes and does
      not suppress anything inside the tree.
    */
    <html lang="en" className={fontVariableClassName} suppressHydrationWarning>
      <head>
        {/*
          First thing in the head, before the stylesheet and before any bundle: the class has
          to be on <html> before the browser paints or the user sees a light page flash to
          dark.
        */}
        <ColorModeScript />
      </head>
      <body>
        <Providers>
          <SkipToContent />
          {/*
            Above the route content and outside both route groups, so the worker is
            registered on the sign-in screen too. Caching the shell before the first
            sign-in is what makes the first offline launch work at all.
          */}
          <ServiceWorkerManager />
          {children}
        </Providers>
      </body>
    </html>
  );
}
