import type { MetadataRoute } from "next";
import { publicConfig } from "@/config/env";

/**
 * Web app manifest, served at `/manifest.webmanifest`.
 *
 * Generated by a route rather than hand-written into `public/` so the name and short name
 * come from `publicConfig` and cannot drift from the rest of the UI. The path is already
 * in `PUBLIC_PATH_PREFIXES` (src/server/auth/auth-config.ts): a manifest behind a login
 * redirect is fetched as HTML, and the browser then silently declines to offer
 * installation with no visible error.
 *
 * `start_url` is `/dashboard` rather than `/`. An installed app should open on something
 * useful, and an unauthenticated launch is redirected to sign-in by middleware anyway.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    id: "/dashboard",
    name: publicConfig.appName,
    short_name: publicConfig.appShortName,
    description: "Track personal and shared expenses, accounts, and settlements.",

    start_url: "/dashboard",
    scope: "/",

    // "standalone" is what makes the installed app feel like an app rather than a tab.
    // `display_override` asks for the newer window-controls-overlay first and degrades
    // silently on browsers that do not know it.
    display: "standalone",
    display_override: ["standalone", "minimal-ui"],
    orientation: "portrait",

    // Matches `surface` in the theme, so the splash screen does not flash a different
    // colour before the app paints.
    background_color: "#ffffff",
    theme_color: "#ffffff",

    categories: ["finance", "productivity", "utilities"],
    lang: "en",
    dir: "ltr",

    icons: [
      {
        src: "/icons/icon.svg",
        sizes: "any",
        type: "image/svg+xml",
        purpose: "any",
      },
      {
        src: "/icons/icon-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icons/icon-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
      // Separate maskable entries: Android crops up to 20% off each edge, and reusing the
      // "any" icons would clip the mark. The maskable renders keep the glyph inside the
      // safe zone.
      {
        src: "/icons/icon-maskable-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "maskable",
      },
      {
        src: "/icons/icon-maskable-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],

    // The two things a user opens the app to do. Long-press on Android, right-click on
    // the desktop taskbar.
    shortcuts: [
      {
        name: "Add expense",
        short_name: "Add",
        url: "/transactions/new",
        icons: [{ src: "/icons/icon-192.png", sizes: "192x192", type: "image/png" }],
      },
      {
        name: "Settle up",
        short_name: "Settle",
        url: "/people",
        icons: [{ src: "/icons/icon-192.png", sizes: "192x192", type: "image/png" }],
      },
    ],
  };
}
